//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilghtsAPILayer.SrvDomesticFlightPricing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://price.flight.arzoo.com", ConfigurationName="SrvDomesticFlightPricing.DOMFlightPricingPortType")]
    public interface DOMFlightPricingPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getPricingDetails(string in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOMFlightPricingPortTypeChannel : FilghtsAPILayer.SrvDomesticFlightPricing.DOMFlightPricingPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOMFlightPricingPortTypeClient : System.ServiceModel.ClientBase<FilghtsAPILayer.SrvDomesticFlightPricing.DOMFlightPricingPortType>, FilghtsAPILayer.SrvDomesticFlightPricing.DOMFlightPricingPortType {
        
        public DOMFlightPricingPortTypeClient() {
        }
        
        public DOMFlightPricingPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOMFlightPricingPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOMFlightPricingPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOMFlightPricingPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getPricingDetails(string in0) {
            return base.Channel.getPricingDetails(in0);
        }
    }
}
