//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilghtsAPILayer.SrvDomesticFlightCancellationStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cancelationstatus.flight.arzoo.com", ConfigurationName="SrvDomesticFlightCancellationStatus.DOMFlightCancellationStatusPortType")]
    public interface DOMFlightCancellationStatusPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getCancelationStatus(string in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOMFlightCancellationStatusPortTypeChannel : FilghtsAPILayer.SrvDomesticFlightCancellationStatus.DOMFlightCancellationStatusPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOMFlightCancellationStatusPortTypeClient : System.ServiceModel.ClientBase<FilghtsAPILayer.SrvDomesticFlightCancellationStatus.DOMFlightCancellationStatusPortType>, FilghtsAPILayer.SrvDomesticFlightCancellationStatus.DOMFlightCancellationStatusPortType {
        
        public DOMFlightCancellationStatusPortTypeClient() {
        }
        
        public DOMFlightCancellationStatusPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOMFlightCancellationStatusPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOMFlightCancellationStatusPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOMFlightCancellationStatusPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getCancelationStatus(string in0) {
            return base.Channel.getCancelationStatus(in0);
        }
    }
}
