//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilghtsAPILayer.SrvDomesticFlightAvailability {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://avail.flight.arzoo.com", ConfigurationName="SrvDomesticFlightAvailability.DOMFlightAvailabilityPortType")]
    public interface DOMFlightAvailabilityPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getAvailability(string in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DOMFlightAvailabilityPortTypeChannel : FilghtsAPILayer.SrvDomesticFlightAvailability.DOMFlightAvailabilityPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DOMFlightAvailabilityPortTypeClient : System.ServiceModel.ClientBase<FilghtsAPILayer.SrvDomesticFlightAvailability.DOMFlightAvailabilityPortType>, FilghtsAPILayer.SrvDomesticFlightAvailability.DOMFlightAvailabilityPortType {
        
        public DOMFlightAvailabilityPortTypeClient() {
        }
        
        public DOMFlightAvailabilityPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DOMFlightAvailabilityPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOMFlightAvailabilityPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DOMFlightAvailabilityPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getAvailability(string in0) {
            return base.Channel.getAvailability(in0);
        }
    }
}
